require 'native'

# body parts
WORK = Native(`WORK`)
CARRY = Native(`CARRY`)
MOVE = Native(`MOVE`)

# finders

FIND_MY_CREEPS = Native(`FIND_MY_CREEPS`)
FIND_EXIT_TOP = Native(`FIND_EXIT_TOP`)
FIND_EXIT_RIGHT = Native(`FIND_EXIT_RIGHT`)
FIND_EXIT_BOTTOM = Native(`FIND_EXIT_BOTTOM`)
FIND_EXIT_LEFT = Native(`FIND_EXIT_LEFT`)
FIND_EXIT = Native(`FIND_EXIT`),
FIND_CREEPS = Native(`FIND_CREEPS`),
FIND_MY_CREEPS = Native(`FIND_MY_CREEPS`),
FIND_HOSTILE_CREEPS = Native(`FIND_HOSTILE_CREEPS`),
FIND_SOURCES_ACTIVE = Native(`FIND_SOURCES_ACTIVE`),
FIND_SOURCES = Native(`FIND_SOURCES`),
FIND_DROPPED_ENERGY = Native(`FIND_DROPPED_ENERGY`),
FIND_DROPPED_RESOURCES = Native(`FIND_DROPPED_RESOURCES`),
FIND_STRUCTURES = Native(`FIND_STRUCTURES`),
FIND_MY_STRUCTURES = Native(`FIND_MY_STRUCTURES`),
FIND_HOSTILE_STRUCTURES = Native(`FIND_HOSTILE_STRUCTURES`),
FIND_FLAGS = Native(`FIND_FLAGS`),
FIND_CONSTRUCTION_SITES = Native(`FIND_CONSTRUCTION_SITES`),
FIND_MY_SPAWNS = Native(`FIND_MY_SPAWNS`),
FIND_HOSTILE_SPAWNS = Native(`FIND_HOSTILE_SPAWNS`),
FIND_MY_CONSTRUCTION_SITES = Native(`FIND_MY_CONSTRUCTION_SITES`),
FIND_HOSTILE_CONSTRUCTION_SITES = Native(`FIND_HOSTILE_CONSTRUCTION_SITES`),
FIND_MINERALS = Native(`FIND_MINERALS`),
FIND_NUKES = Native(`FIND_NUKES`),
FIND_TOMBSTONES = Native(`FIND_TOMBSTONES`)
